import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";

function AssertionViewer() {

    const navigate = useNavigate();

    const [assertion, setAssertion] = useState("");

    useEffect(() => {

        const xml = localStorage.getItem("assertion");

        if (!xml) {

            navigate("/hr/dashboard");
            return;

        }

        setAssertion(xml);

    }, [navigate]);

    return (

        <div className="max-w-7xl mx-auto p-12">

            <div className="bg-[#131922] border border-[#232B36] rounded-md p-10">

                <p className="font-['IBM_Plex_Mono'] text-xs tracking-widest text-[#4FD1C5] uppercase mb-3">
                    IdP Response
                </p>

                <h1 className="font-['IBM_Plex_Mono'] text-3xl font-bold text-[#E6EAF0]">

                    SAML Assertion

                </h1>

                <p className="font-['IBM_Plex_Sans'] text-sm text-[#8A94A3] mt-3">

                    Generated by SAMLGuard Identity Provider

                </p>

                <div className="grid md:grid-cols-2 gap-6 mt-10">

                    <div className="bg-[#0B0F14] border border-[#232B36] rounded-md p-6">

                        <h2 className="font-['IBM_Plex_Mono'] text-sm tracking-widest uppercase text-[#8A94A3] mb-6">

                            Assertion Information

                        </h2>

                        <div className="space-y-4 font-['IBM_Plex_Sans'] text-sm">

                            <div className="flex justify-between border-b border-[#232B36] pb-3">
                                <span className="text-[#8A94A3]">Issuer</span>
                                <span className="text-[#E6EAF0]">SAMLGuard Identity Provider</span>
                            </div>

                            <div className="flex justify-between border-b border-[#232B36] pb-3">
                                <span className="text-[#8A94A3]">Subject</span>
                                <span className="text-[#E6EAF0]">Authenticated User</span>
                            </div>

                            <div className="flex justify-between border-b border-[#232B36] pb-3">
                                <span className="text-[#8A94A3]">Version</span>
                                <span className="text-[#E6EAF0]">2.0</span>
                            </div>

                            <div className="flex justify-between items-center">
                                <span className="text-[#8A94A3]">Status</span>
                                <span className="font-['IBM_Plex_Mono'] text-xs text-[#4FD1C5] border border-[#4FD1C5]/40 px-3 py-1 rounded-full">
                                    Valid
                                </span>
                            </div>

                        </div>

                    </div>

                    <div className="bg-[#0B0F14] border border-[#232B36] rounded-md p-6 overflow-auto">

                        <h2 className="font-['IBM_Plex_Mono'] text-sm tracking-widest uppercase text-[#8A94A3] mb-6">

                            Raw XML

                        </h2>

                        <pre className="font-['IBM_Plex_Mono'] text-[#4FD1C5] whitespace-pre-wrap text-xs leading-relaxed">

{assertion}

                        </pre>

                    </div>

                </div>

                <div className="mt-10 flex gap-4">

                    <button

                        onClick={() => navigate("/hr/dashboard")}

                        className="font-['IBM_Plex_Mono'] text-sm bg-[#4FD1C5] text-[#0B0F14] font-semibold px-6 py-3 rounded-md hover:bg-[#4FD1C5]/90 transition-colors"

                    >

                        Back to Dashboard

                    </button>

                    <button

                        onClick={() => navigator.clipboard.writeText(assertion)}

                        className="font-['IBM_Plex_Mono'] text-sm border border-[#232B36] text-[#E6EAF0] px-6 py-3 rounded-md hover:bg-[#232B36] transition-colors"

                    >

                        Copy XML

                    </button>

                </div>

            </div>

        </div>

    );

}

export default AssertionViewer;