import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";

function AssertionViewer() {

    const navigate = useNavigate();

    const [assertion, setAssertion] = useState("");

    useEffect(() => {

        const xml = localStorage.getItem("assertion");

        if (!xml) {

            navigate("/hr/dashboard");
            return;

        }

        setAssertion(xml);

    }, [navigate]);

    return (

        <div className="min-h-screen bg-slate-100 p-10">

            <div className="max-w-7xl mx-auto">

                <div className="bg-white rounded-2xl shadow-xl p-10">

                    <h1 className="text-5xl font-bold text-slate-800">

                        SAML Assertion

                    </h1>

                    <p className="text-gray-500 mt-3">

                        Generated by SAMLGuard Identity Provider

                    </p>

                    <hr className="my-8" />

                    <div className="grid md:grid-cols-2 gap-8">

                        <div className="bg-slate-50 rounded-xl p-6">

                            <h2 className="text-2xl font-bold mb-6">

                                Assertion Information

                            </h2>

                            <div className="space-y-4">

                                <div>

                                    <p className="font-semibold">

                                        Issuer

                                    </p>

                                    <p>SAMLGuard Identity Provider</p>

                                </div>

                                <div>

                                    <p className="font-semibold">

                                        Subject

                                    </p>

                                    <p>Authenticated User</p>

                                </div>

                                <div>

                                    <p className="font-semibold">

                                        Version

                                    </p>

                                    <p>2.0</p>

                                </div>

                                <div>

                                    <p className="font-semibold">

                                        Status

                                    </p>

                                    <span className="bg-green-100 text-green-700 px-3 py-1 rounded-full">

                                        Valid

                                    </span>

                                </div>

                            </div>

                        </div>

                        <div className="bg-slate-900 rounded-xl p-6 overflow-auto">

                            <h2 className="text-2xl font-bold text-white mb-6">

                                Raw XML

                            </h2>

                            <pre className="text-green-400 whitespace-pre-wrap text-sm">

{assertion}

                            </pre>

                        </div>

                    </div>

                    <div className="mt-10 flex gap-5">

                        <button

                            onClick={() => navigate("/hr/dashboard")}

                            className="bg-blue-600 text-white px-8 py-3 rounded-xl hover:bg-blue-700"

                        >

                            Back to Dashboard

                        </button>

                        <button

                            onClick={() => navigator.clipboard.writeText(assertion)}

                            className="bg-slate-700 text-white px-8 py-3 rounded-xl hover:bg-slate-800"

                        >

                            Copy XML

                        </button>

                    </div>

                </div>

            </div>

        </div>

    );

}

export default AssertionViewer;